config/routes.rb
Rails.application.routes.draw do
  namespace('tolk') do
    root :to => 'locales#index'
    resources :locales do
      member do
        get :all
        get :updated
      end
    end
    resource :search
  end
end

app/models/tolk/locale.rb
module Tolk
  class Locale < ActiveRecord::Base
    set_table_name "tolk_locales"

    MAPPING = {
      'ar'    => 'Arabic',
      'bs'    => 'Bosnian',
      'bt'    => 'Bulgarian',
      'ca'    => 'Catalan',
      'cz'    => 'Czech',
      'da'    => 'Danish',
      'de'    => 'German',
      'dsb'   => 'Lower Sorbian',
      'el'    => 'Greek',
      'en'    => 'English',
      'es'    => 'Spanish',
      'et'    => 'Estonian',
      'fa'    => 'Persian',
      'fi'    => 'Finnish',
      'fr'    => 'French',
      'he'    => 'Hebrew',
      'hr'    => 'Croatian',
      'hsb'   => 'Upper Sorbian',
      'hu'    => 'Hungarian',
      'id'    => 'Indonesian',
      'is'    => 'Icelandic',
      'it'    => 'Italian',
      'jp'    => 'Japanese',
      'ko'    => 'Korean',
      'lo'    => 'Lao',
      'lt'    => 'Lithuanian',
      'lv'    => 'Latvian',
      'mk'    => 'Macedonian',
      'nl'    => 'Dutch',
      'no'    => 'Norwegian',
      'pl'    => 'Polish',
      'pt-BR' => 'Portuguese (Brazilian)',
      'pt-PT' => 'Portuguese (Portugal)',
      'ro'    => 'Romanian',
      'ru'    => 'Russian',
      'se'    => 'Swedish',
      'sk'    => 'Slovak',
      'sl'    => 'Slovenian',
      'sr'    => 'Serbian',
      'sw'    => 'Swahili',
      'th'    => 'Thai',
      'tr'    => 'Turkish',
      'uk'    => 'Ukrainian',
      'vi'    => 'Vietnamese',
      'zh'    => 'Chinese'
    }

    has_many :phrases, :through => :translations, :class_name => 'Tolk::Phrase'
    has_many :translations, :class_name => 'Tolk::Translation', :dependent => :destroy
    accepts_nested_attributes_for :translations, :reject_if => proc { |attributes| attributes['text'].blank? }
    before_validation :remove_invalid_translations_from_target, :on => :update

    cattr_accessor :locales_config_path
    self.locales_config_path = "#{Rails.root}/config/locales"

    cattr_accessor :primary_locale_name
    self.primary_locale_name = I18n.default_locale.to_s

    include Tolk::Sync
    include Tolk::Import

    validates_uniqueness_of :name
    validates_presence_of :name

    cattr_accessor :special_prefixes
    self.special_prefixes = ['activerecord.attributes']

    cattr_accessor :special_keys
    self.special_keys = ['activerecord.models']

    class << self
      def primary_locale(reload = false)
        @_primary_locale = nil if reload
        @_primary_locale ||= begin
          raise "Primary locale is not set. Please set Locale.primary_locale_name in your application's config file" unless self.primary_locale_name
          find_or_create_by_name(self.primary_locale_name)
        end
      end

      def primary_language_name
        primary_locale.language_name
      end

      def secondary_locales
        all - [primary_locale]
      end

      def dump_all(to = self.locales_config_path)
        secondary_locales.each do |locale|
          File.open("#{to}/#{locale.name}.yml", "w+") do |file|
            data = locale.to_hash
            data.respond_to?(:ya2yaml) ? file.write(data.ya2yaml(:syck_compatible => true)) : YAML.dump(locale.to_hash, file)
          end
        end
      end

      def special_key_or_prefix?(prefix, key)
        self.special_prefixes.include?(prefix) || self.special_keys.include?(key)
      end

      PLURALIZATION_KEYS = ['zero', 'one', 'two', 'few', 'many', 'other']
      def pluralization_data?(data)
        keys = data.keys.map(&:to_s)
        keys.all? {|k| PLURALIZATION_KEYS.include?(k) }
      end
    end

    def has_updated_translations?
      translations.count(:conditions => {:'tolk_translations.primary_updated' => true}) > 0
    end

    def phrases_with_translation(page = nil)
      find_phrases_with_translations(page, :'tolk_translations.primary_updated' => false)
    end

    def phrases_with_updated_translation(page = nil)
      find_phrases_with_translations(page, :'tolk_translations.primary_updated' => true)
    end

    def count_phrases_without_translation
      existing_ids = self.translations.all(:select => 'tolk_translations.phrase_id').map(&:phrase_id).uniq
      Tolk::Phrase.count - existing_ids.count
    end

    def phrases_without_translation(page = nil, options = {})
      phrases = Tolk::Phrase.scoped(:order => 'tolk_phrases.key ASC')

      existing_ids = self.translations.all(:select => 'tolk_translations.phrase_id').map(&:phrase_id).uniq
      phrases = phrases.scoped(:conditions => ['tolk_phrases.id NOT IN (?)', existing_ids]) if existing_ids.present?

      result = phrases.paginate({:page => page}.merge(options))
      Tolk::Phrase.send :preload_associations, result, :translations
      result
    end

    def search_phrases(query, scope, page = nil, options = {})
      return [] unless query.present?

      translations = case scope
      when :origin
        Tolk::Locale.primary_locale.translations.containing_text(query)
      else # :target
        self.translations.containing_text(query)
      end

      phrases = Tolk::Phrase.scoped(:order => 'tolk_phrases.key ASC')      
      phrases = phrases.scoped(:conditions => ['tolk_phrases.id IN(?)', translations.map(&:phrase_id).uniq])
      phrases.paginate({:page => page}.merge(options))
    end
    
    def search_phrases_without_translation(query, page = nil, options = {})
      return phrases_without_translation(page, options) unless query.present?
      
      phrases = Tolk::Phrase.scoped(:order => 'tolk_phrases.key ASC')

      found_translations_ids = Tolk::Locale.primary_locale.translations.all(:conditions => ["tolk_translations.text LIKE ?", "%#{query}%"], :select => 'tolk_translations.phrase_id').map(&:phrase_id).uniq
      existing_ids = self.translations.all(:select => 'tolk_translations.phrase_id').map(&:phrase_id).uniq
      phrases = phrases.scoped(:conditions => ['tolk_phrases.id NOT IN (?) AND tolk_phrases.id IN(?)', existing_ids, found_translations_ids]) if existing_ids.present?

      result = phrases.paginate({:page => page}.merge(options))
      Tolk::Phrase.send :preload_associations, result, :translations
      result
    end

    def to_hash
      { name => translations.each_with_object({}) do |translation, locale|
        if translation.phrase.key.include?(".")
          locale.deep_merge!(unsquish(translation.phrase.key, translation.value))
        else
          locale[translation.phrase.key] = translation.value
        end
      end }
    end

    def to_param
      name.parameterize
    end

    def primary?
      name == self.class.primary_locale_name
    end

    def language_name
      MAPPING[self.name] || self.name
    end

    def [](key)
      if phrase = Tolk::Phrase.find_by_key(key)
        t = self.translations.find_by_phrase_id(phrase.id)
        t.text if t
      end
    end

    def translations_with_html
      translations = self.translations.all(:conditions => "tolk_translations.text LIKE '%>%' AND 
        tolk_translations.text LIKE '%<%' AND tolk_phrases.key NOT LIKE '%_html'", :joins => :phrase)
      Translation.send :preload_associations, translations, :phrase
      translations
    end

    private

    def remove_invalid_translations_from_target
      self.translations.proxy_target.each do |t|
        unless t.valid?
          self.translations.proxy_target.delete(t)
        else
          t.updated_at = Time.current # Silly hax to fool autosave into saving the record
        end
      end

      true
    end

    def find_phrases_with_translations(page, conditions = {})
      result = Tolk::Phrase.paginate(:page => page,
        :conditions => { :'tolk_translations.locale_id' => self.id }.merge(conditions),
        :joins => :translations, :order => 'tolk_phrases.key ASC')

      Tolk::Phrase.send :preload_associations, result, :translations

      result.each do |phrase|
        phrase.translation = phrase.translations.for(self)
      end

      result
    end

    def unsquish(string, value)
      if string.is_a?(String)
        unsquish(string.split("."), value)
      elsif string.size == 1
        { string.first => value }
      else
        key  = string[0]
        rest = string[1..-1]
        { key => unsquish(rest, value) }
      end
    end
  end
end

app/models/tolk/phrase.rb
module Tolk
  class Phrase < ActiveRecord::Base
    set_table_name "tolk_phrases"

    validates_uniqueness_of :key

    cattr_accessor :per_page
    self.per_page = 30

    has_many :translations, :class_name => 'Tolk::Translation', :dependent => :destroy do
      def primary
        to_a.detect {|t| t.locale_id == Tolk::Locale.primary_locale.id}
      end

      def for(locale)
        to_a.detect {|t| t.locale_id == locale.id}
      end
    end

    attr_accessor :translation
  end
end

app/models/tolk/translation.rb
module Tolk
  class Translation < ActiveRecord::Base
    set_table_name "tolk_translations"

    scope :containing_text, lambda {|query| where("tolk_translations.text LIKE ?", "%#{query}%") }

    serialize :text
    validates_presence_of :text, :if => proc {|r| r.primary.blank? && !r.explicit_nil }
    validate :check_matching_variables, :if => proc { |tr| tr.primary_translation.present? }

    validates_uniqueness_of :phrase_id, :scope => :locale_id

    belongs_to :phrase, :class_name => 'Tolk::Phrase'
    belongs_to :locale, :class_name => 'Tolk::Locale'

    attr_accessor :force_set_primary_update
    before_save :set_primary_updated

    before_save :set_previous_text

    attr_accessor :primary
    before_validation :fix_text_type, :unless => proc {|r| r.primary }

    attr_accessor :explicit_nil
    before_validation :set_explicit_nil

    def up_to_date?
      not out_of_date?
    end

    def out_of_date?
      primary_updated?
    end

    def primary_translation
      @_primary_translation ||= begin
        if locale && !locale.primary?
          phrase.translations.primary
        end
      end
    end

    def text=(value)
      super unless value.to_s == text
    end

    def value
      if text.is_a?(String) && /^\d+$/.match(text)
        text.to_i
      else
        text
      end
    end

    def self.detect_variables(search_in)
      case search_in
        when String then Set.new(search_in.scan(/\{\{(\w+)\}\}/).flatten + search_in.scan(/\%\{(\w+)\}/).flatten) 
        when Array then search_in.inject(Set[]) { |carry, item| carry + detect_variables(item) }
        when Hash then search_in.values.inject(Set[]) { |carry, item| carry + detect_variables(item) }
        else Set[]
      end
    end

    def variables
      self.class.detect_variables(text)
    end

    def variables_match?
      self.variables == primary_translation.variables
    end

    private

    def set_explicit_nil
      if self.text == '~'
        self.text = nil
        self.explicit_nil = true
      end
    end

    def fix_text_type
      if primary_translation.present?
        if self.text.is_a?(String) && !primary_translation.text.is_a?(String)
          self.text = begin
            YAML.load(self.text.strip)
          rescue ArgumentError
            nil
          end

        end

        self.text = nil if primary_translation.text.class != self.text.class
      end

      true
    end

    def set_primary_updated
      self.primary_updated = self.force_set_primary_update ? true : false
      true
    end

    def set_previous_text
      self.previous_text = self.text_was if text_changed?
      true
    end

    def check_matching_variables
      unless variables_match?
        if primary_translation.variables.empty?
          self.errors.add(:text, "The original does not contain variables, so they should not be included.")
        else
          self.errors.add(:text, "The translation should contain the variables #{variables.to_a.to_sentence}.")
        end
      end
    end
  end
end

app/controllers/tolk/application_controller.rb
module Tolk
  class ApplicationController < ActionController::Base
    helper :all
    protect_from_forgery

    cattr_accessor :authenticator
    before_filter :authenticate

    def authenticate
      self.authenticator.bind(self).call if self.authenticator && self.authenticator.respond_to?(:call)
    end

    def ensure_no_primary_locale
      redirect_to tolk_locales_path if @locale.primary?
    end
  end
end

app/controllers/tolk/locales_controller.rb
module Tolk
  class LocalesController < Tolk::ApplicationController
    before_filter :find_locale, :only => [:show, :all, :update, :updated]
    before_filter :ensure_no_primary_locale, :only => [:all, :update, :show, :updated]

    def index
      @locales = Tolk::Locale.secondary_locales
    end
  
    def show
      respond_to do |format|
        format.html do
          @phrases = @locale.phrases_without_translation(params[:page])
        end
        format.atom { @phrases = @locale.phrases_without_translation(params[:page], :per_page => 50) }
        format.yaml { render :text => @locale.to_hash.ya2yaml(:syck_compatible => true) }
      end
    end

    def update
      @locale.translations_attributes = params[:translations]
      @locale.save
      redirect_to request.referrer
    end

    def all
      @phrases = @locale.phrases_with_translation(params[:page])
    end

    def updated
      @phrases = @locale.phrases_with_updated_translation(params[:page])
      render :all
    end

    def create
      Tolk::Locale.create!(params[:tolk_locale])
      redirect_to :action => :index
    end

    private

    def find_locale
      @locale = Tolk::Locale.find_by_name!(params[:id])
    end
  end
end

app/controllers/tolk/searches_controller.rb
module Tolk
  class SearchesController < Tolk::ApplicationController
    before_filter :find_locale
  
    def show
      @phrases = @locale.search_phrases(params[:q], params[:scope].to_sym, params[:page])
    end

    private

    def find_locale
      @locale = Tolk::Locale.find_by_name!(params[:locale])
    end
  end
end

app/helpers/tolk/application_helper.rb
module Tolk
  module ApplicationHelper
    def format_i18n_value(value)
      h(yaml_value(value)).gsub(/\n/, '<br />')
    end

    def format_i18n_text_area_value(value)
      yaml_value(value)
    end

    def yaml_value(value)
      if value.present?
        unless value.is_a?(String)
          value = value.respond_to?(:ya2yaml) ? value.ya2yaml(:syck_compatible => true) : value.to_yaml
        end
      end
      
      value
    end

    def tolk_locale_selection
      existing_locale_names = Tolk::Locale.all.map(&:name)

      pairs = Tolk::Locale::MAPPING.to_a.map(&:reverse).sort_by(&:first)
      pairs.reject {|pair| existing_locale_names.include?(pair.last) }
    end

    def scope_selector_for(locale)
      select_tag 'scope', options_for_select([[Tolk::Locale.primary_locale.language_name, "origin"],
                                              [locale.language_name, "target"]], params[:scope])
    end
  end
end

app/views/tolk/locales/all.html.erb
<% content_for :locale do %><span class="locale"><%= @locale.language_name %></span>
<% end %>

<h3 class="switch">Completed translations <span>(<%= link_to 'See phrases missing translation', @locale %>)</span></h3>

<% if @locale.has_updated_translations? && action_name != 'updated' %>
  <span class="notice">Some phrases have changed. <%= link_to "Update translations", updated_tolk_locale_path(@locale) %>.</span>
<% end %>

<div class="search">
  <%= render :partial => "tolk/searches/form", :locals => { :locale => @locale } %>
</div>

<div class="translations">
<% if @phrases.any? %>
  <%= form_for @locale do |locale_form| %>
        <table class="translations">
      <tr>
        <th class="translation"><%= @locale.language_name -%></th>
        <th class="key"><%= Tolk::Locale.primary_language_name -%></th>
      </tr>
      <% @phrases.each do |phrase| %>
        <% if phrase.translations.primary %>
          <tr>
            <td class="translation">
              <%= hidden_field_tag :"translations[][id]", phrase.translation.id %>
              <%= hidden_field_tag :"translations[][locale_id]", phrase.translation.locale_id %>
              <%= text_area_tag :"translations[][text]", format_i18n_text_area_value(phrase.translation.text), :class => 'locale',
                                :onfocus => "$(this).up('tr').addClassName('active');", :onblur => "$(this).up('tr').removeClassName('active');" %>
            </td>
            <td class="phrase">

              <% if action_name == 'updated' %>
                <div class="updated">
                  <span class="key">Updated</span>
                  <%= format_i18n_value(phrase.translations.primary.text) -%>
                </div>
                <div class="original">
                  <span class="key">Original</span>
                  <%= format_i18n_value(phrase.translations.primary.previous_text) -%>
                </div>
              <% else %>
                <%= format_i18n_value(phrase.translations.primary.text) -%>
              <% end %>

              <span class="key"><%= phrase.key %></span>
            </td>
          </tr>
        <% end %>
      <% end %>
    </table>
    <div class="table_submit">
      <p><%= locale_form.submit "Save changes" %></p>
    </div>
    <div class="paginate">
      <%= will_paginate @phrases %>
    </div>
  <% end %>
<% else %>
  <p style="text-align: left">There aren't any completed translations for this locale.</p>
  <p>&nbsp;</p>
<% end %>
</div>

app/views/tolk/locales/index.html.erb
<% content_for :locale do %><span class="locale empty"></span>
<% end %>

<h2>Locales <span>Primary locale is <%= Tolk::Locale.primary_locale.language_name %></span></h2>
<% if @locales.any? %>
  <ul class="locales clearfix">
    <% @locales.each do |locale| %>
      <li>
        <%= link_to locale.language_name, locale %>
        <% missing_count = locale.count_phrases_without_translation %>
        <% if missing_count > 0 %>
          <span class="missing_translations"><%= locale.count_phrases_without_translation %></span>
        <% end %>
      </li>
    <% end %>
  </ul>
  
<% else %>
  <p>No locales yet.</p>

<% end %>
<%= form_for(Tolk::Locale.new) do |f| %>
<div class="submit">
  <%= f.error_messages %>
  <p>
    <%= f.label "Add a new Locale" %>
    <select id="select_tolk_locale_name" name="tolk_locale[name]">
      <%= options_for_select tolk_locale_selection %>
    </select>
    <%= f.submit 'Add' %>
  </p>
</div>
<% end %>

app/views/tolk/locales/show.html.erb
<% content_for :locale do %>
  <span class="locale"><%= @locale.language_name %></span>
<% end %>

<% content_for :head do %>
  <link rel="alternate" type="application/rss+xml" title="RSS" href="<%= tolk_locale_path(@locale, :format => 'atom') -%>" />
<% end %>

<h3 class="switch">Phrases missing translation (<%= @locale.count_phrases_without_translation %>) <span>(<%= link_to 'See completed translations', all_tolk_locale_path(@locale) %>)</span></h3>

<% if @locale.has_updated_translations? && action_name != 'updated' %>
  <span class="notice">Some phrases have changed. <%= link_to "Update translations", updated_tolk_locale_path(@locale) %>.</span>
<% end %>

<div class="search">
  <%= render :partial => "tolk/searches/form", :locals => { :locale => @locale } %>
</div>

<div class="translations">
  <% if @phrases.any? %>
     <%= form_for @locale do |locale_form| %>
      <table class="translations">
        <tr>
          <th class="translation"><%= @locale.language_name -%></th>
          <th class="key"><%= Tolk::Locale.primary_language_name -%></th>
        </tr>
        <% @phrases.each do |phrase| %>
          <tr>
            <% translation = Tolk::Translation.new(:locale => @locale, :phrase => phrase) %>
            <td class="translation">
              <%= hidden_field_tag :"translations[][id]", translation.id, :id => "#{translation.object_id}_id" %>
              <%= hidden_field_tag :"translations[][phrase_id]", phrase.id, :id => "#{translation.object_id}_phrase_id" %>
              <%= hidden_field_tag :"translations[][locale_id]", translation.locale_id, :id => "#{translation.object_id}_locale_id" %>
              <%= text_area_tag :"translations[][text]", format_i18n_text_area_value(translation.text), :class => "locale", :id => "#{translation.object_id}_text", :onfocus => "$(this).up('tr').addClassName('active');", :onblur => "$(this).up('tr').removeClassName('active');" %>
            </td>
            <td class="phrase">
              <% if params[:q].present? -%>
                <%= highlight(format_i18n_value(phrase.translations.primary.text), params[:q]) -%>
              <% else -%>
                <%= format_i18n_value(phrase.translations.primary.text) -%>
              <% end -%>
              <span class="key" title="<%= phrase.key %>"><%= truncate(phrase.key, :length => 100) %></span>
            </td>
          </tr>
        <% end %>
      </table>
      <div class="table_submit">
        <p><%= locale_form.submit "Save changes" %></p>
      </div>
    <% end %>
    <div class="paginate">
      <%= will_paginate @phrases %>
    </div>
  <% else %>
    <p style="text-align: left">There aren't any missing or updated phrases that need translation.</p>
    <p>&nbsp;</p>
  <% end %>
</div>